# Generated by Django 4.2 on 2025-05-20 19:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_url',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.face_url_path),
        ),
    ]
