# Generated by Django 4.2 on 2025-02-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
