# Generated by Django 4.2 on 2025-02-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_max_otp_try_user_otp_user_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_require',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_otp_try',
            field=models.IntegerField(default=3),
        ),
    ]
