# Generated by Django 4.2 on 2025-03-07 12:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_status', models.CharField(choices=[('Ordered', 'Ordered'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], max_length=15)),
                ('receiver_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_code', models.CharField(max_length=50, unique=True)),
                ('shipment_type', models.CharField(choices=[('Food', 'Food'), ('Cloth', 'Cloth'), ('Electronic', 'Electronic')], max_length=20)),
                ('size', models.CharField(choices=[('Small', 'S'), ('Medium', 'M'), ('Large', 'L'), ('X-large', 'Xl')], max_length=10)),
                ('weight', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('shipment', models.ForeignKey(db_column='shipment_code', on_delete=django.db.models.deletion.CASCADE, to='orders.shipment', to_field='shipment_code')),
            ],
        ),
    ]
