# Generated by Django 4.2 on 2025-03-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipment_code',
        ),
    ]
