# Generated by Django 4.2 on 2025-05-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='receiver_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender_phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
