# Generated by Django 4.2 on 2025-03-02 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_remove_order_shipment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='sender',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='deliverer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
    ]
