# Generated by Django 4.2 on 2025-05-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shipment_receiver_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cod'), ('vietqr', 'Vietqr')], max_length=15),
        ),
    ]
